## Make Effect Size Figure For El Nino Meta-analysis ##

## You need to set your working directory to be within the GitHub repo "ElNino_MetaAnalysis" to proceed with the following filepaths.

# Load El Niño data generated by "data/ElNinoMetaAnalysis_code.R"
load(file="data/ElNino.RData")

# Setup
tiff(filename = "figures/Fig4.tiff", # Open tiff file
     width = 2250, height= 1286, units = "px", # Set tiff size
     compression = "lzw", res = 300) # Set compression and resolution
par(mar=c(0,0,0,0)) # Set the margins all to 0
par(mai=c(.3,.2,.2,.2)) # Set the distance (in inches) between panels
layout(matrix(c(1,2,1,3),nrow=2), widths=c(1,1,2), heights=c(1.5,2,2)) # Set up the layout for a 3-panel plot
darkred <- col2rgb("darkred") # Extract rgb values from darkred
darkredlight <- rgb((darkred[1]/255),(darkred[2]/255),(darkred[3])/255,.75) # Create a semi-transparent darkred

# Panel 1 (Overall Models)
all.cov <- cover.rma.1yr$b[1] # Extract the effect size of the overall cover model
all.bl <- bleaching.rma$b[1] # Extract the effect size of the overall bleaching model
overall <- c(all.bl, all.cov) # Concatenate all estimates so they can be plotted
lb.res.cov <- c(cover.rma.1yr$ci.lb) # Extract the lower bound of the overall cover model
ub.res.cov <- c(cover.rma.1yr$ci.ub) # Extract the upper bound of the overall cover model

lb.res.bl <- c(bleaching.rma$ci.lb) # Extract the lower bound of the overall bleaching model
ub.res.bl <- c(bleaching.rma$ci.ub) # Extract the upper bound of the overall bleaching model
plot(c(-2.5,2.5), c(0,5.5), type="n", xlab="", ylab="", yaxt="n", 
     cex.axis=0.75, tck=0.0235, mgp=c(0,0,0), ylim=c(0,1)) # Initialize plot with x-axes from -2.5 to 2.5, y-axes from 0 to 5.5, no specified type, initialize empty x and y labels, do not plot y-axis, make the axis 0.75x (smaller), specify tick mark size, specify margin line, specify ylim
abline(v=0, lty=2, col="black") # Insert dotted line along x=0
points(overall, c(0.7, 0.3), pch=c(16, 16), # Plot effect size points (from "overall"), specify location on y-axis, specify symbol type
      cex=c(2.5,2.5), col=c("black","darkred"), lwd=c(5,5)) # Set the color of each point, and the line width of each point
      
      
lines(c(lb.res.bl, ub.res.bl), c(0.7,0.7), # Create a line of 95% CI, specify location on y-axis
      col="black", cex=2.5,lwd=5) # Set the color, size, and linewidth
lines(c(lb.res.cov, ub.res.cov), c(0.3,0.3), # Create line of 95% CI, specify location on y-axis
      col="darkred", cex=2.5,lwd=5) # Set the color, size, and linewidth
      
text(2.2, .7, labels="Bleaching*", cex=1.3, col="black") # Add text, specify size and color
text(2.2, .3, labels="Cover**", cex=1.3, col="darkred") # Add text, specify size and color
text(-2.58, 0.875, labels="a)", cex=1.5) # Add label for figure, specify size
mtext(paste("Standardized Mean Difference", "\u00B1", "95% CI"),
      side=1,line=0.75,cex=0.7) # Add in x-axis legend, specify location and size

# Panel 2 (Bleaching model with moderators)
full.bl <- bl.est[c(2:3),] # Extract the effect size of the bleaching model with moderators
lb.bl.tmean <- bl.lb[2,2] # Extract the lower bound of the bleaching model moderator 
lb.bl.TimeLagDHW <- bl.lb[2,3] # Extract the lower bound of the bleaching model moderator 
ub.bl.tmean <- bl.ub[2,2] # Extract the upper bound of the bleaching model moderator
ub.bl.TimeLagDHW <- bl.ub[2,3] # Extract the upper bound of the bleaching model moderator 
plot(c(-1.1,1.1), c(0,5.5), type="n", xlab="", ylab="", 
     yaxt="n", cex.axis=0.75, tck=0.0235, mgp=c(0,0,0), ylim=c(0.15,0.5)) # Initialize plot with x-axes from -0.13 to 0.18,y-axes from 0 to 5.5, no specified type, initialize empty x and y labels, do not plot y-axis make the axis 0.75x (smaller), specify tick mark size, specify margin line, specify ylim 
abline(v=0, lty=2, col="black") # Insert dotted line along x=0
points(full.bl[2:1], c(0.38, .22), pch=c(16, 16), # Plot effect size points (from "full.bl"), specify location on y-axis, specify symbol type
       cex=1.5, col=c("black","black"), lwd=c(2,2)) # Set the color, size, and linewidth

lines(c(lb.bl.TimeLagDHW, ub.bl.TimeLagDHW), c(0.38,0.38), # Create line of 95% CI, specify location on y-axis
      col="black", cex=2.5,lwd=5) # Set the color and line width of each point
lines(c(lb.bl.tmean, ub.bl.tmean), c(0.22,0.22), # Create line of 95% CI, specify loc. on y-axis
      col="black", cex=2.5,lwd=5) # Set the color, size, and linewidth

text(-0.5, .38, labels="TimeLag:MaxDHW*", cex=1, col="black") # Add text, specify size and color
text(-0.5, .22, labels="SSTmean*", cex=1, col="black") # Add text, specify size and color
text(-1.1, 0.477, labels="b)", cex=1.4) # Add label for figure, specify size
text(.8, 0.477, labels="Bleaching", cex=1.5) # Add labelname for figure, specify size
mtext(paste("Standardized Mean Difference", "\u00B1", "95% CI"),
      side=1,line=0.75,cex=0.7) # Add in x-axis legend, specify location and size

# Panel 3 (Cover model with moderators)
full.cov <- cov.1yr.est[2:3,] # Extract the effect size of the cover model with moderators
lb.cov.DHWtodate <- cov.1yr.lb[2,2] # Extract the lower bound of the cover model moderator
lb.cov.tmean <- cov.1yr.lb[2,3] # Extract the lower bound of the cover model moderator 
ub.cov.DHWtodate <- cov.1yr.ub[2,2] # Extract the upper bound of the cover model moderator
ub.cov.tmean <- cov.1yr.ub[2,3] # Extract the upper bound of the cover model moderator tmean
plot(c(-1.1,1.1), c(0,5.5), type="n", xlab="", ylab="", 
     yaxt="n", cex.axis=0.75, tck=0.0235, mgp=c(0,0,0), ylim=c(.15,.5))  # Initialize plot with x-axes from -0.13 to 0.18,y-axes from 0 to 5.5, no specified type, initialize empty x and y labels, do not plot y-axis make the axis 0.75x (smaller), specify tick mark size, specify margin line, specify ylim 
abline(v=0, lty=2, col="black") # Insert dotted line along x=0
points(full.cov, c(0.38, .22), pch=c(16, 16), # Plot effect size points, specify location on y-axis, specify symbol type
       cex=1.5, col=c("darkred","darkred"),lwd=c(2,2)) # Set the color, size, and linewidth

# Plot effect size points (from "full.cov"), specify location on y-axis, specify symbol type
# Set the color of each point, and the line width of each point
lines(c(lb.cov.DHWtodate, ub.cov.DHWtodate), c(0.38,0.38), # Create a line of the 95% CI, specify location on y-axis
      col="darkred", cex=2.5,lwd=5) # Set the color, size, and linewidth

lines(c(lb.cov.tmean, ub.cov.tmean), c(0.22,0.22), # Create a line of the 95% CI, specify location on y-axis
      col="darkred", cex=2.5,lwd=5) # Set the color, size, and linewidth

text(0.5, .38, labels="MaxDHW***", cex=1, col="darkred") # Add text, specify size and color
text(0.5, .22, labels="SSTmean***", cex=1, col="darkred") # Add text, specify size and color
text(-1.1, 0.477, labels="c)", cex=1.4) # Add label for figure, specify size
text(0.9, 0.477, labels="Cover", cex=1.5) # Add labelname "Cover" for figure, specify size
mtext(paste("Standardized Mean Difference", "\u00B1", "95% CI"),
      side=1,line=0.75,cex=0.7) # Add in x-axis legend, specify location and size

dev.off() # Close tiff image, and reset par to defaults
